### PR TITLE
protonmail: Decrypt private keys for all available addresses.

### LINKED ISSUE #14: smtp: support non-primary addresses
Only primary addresses are supported right now.

### LINKED ISSUE #34: blame it on the weather: sender address key hasn\'t been decrypted'
Error in SMTP using nodemailer. Checked in the code. Looks like the private key is null after decryption..

Anything I could do to fix this?

Something goes wrong in this code

`var privateKey *openpgp.Entity
	for _, e := range u.privateKeys {
		if e.PrimaryKey.KeyId == encryptedPrivateKey.PrimaryKey.KeyId {
			privateKey = e
			break
		}
	}
	if privateKey == nil {
		return errors.New("sender address key hasn't been decrypted")
	}`

Here's my nodemailer config if it can help.

`let transporterSale= nodemailer.createTransport({
    host:'127.0.0.1',
    port:1025,
    secure:false,
    auth:{user:"USER",pass:"BRIDGEPW"},
    tls:{rejectUnauthorized:false}
})`

Merci

### PR DESCRIPTION
**Pull request by scelaris**
Workaround for #14 and #34 to allow sending from any address associated with a Protonmail account.

Fixes #14
Fixes #34

### CODE REVIEW

File: protonmail/auth.go [hunk 1]
```diff
@@ -260,6 +260,53 @@ func (c *Client) Unlock(auth *Auth, passphrase string) (openpgp.EntityList, erro
 	c.uid = auth.UID
 	c.accessToken = string(accessTokenBytes)
 	c.keyRing = keyRing
+
+	// Get additional private keys
+	u, err := c.GetCurrentUser()
```
Comment (emersion) [inline protonmail/auth.go]: I've added `Client.ListAddresses` in a recent commit: https://github.com/emersion/hydroxide/commit/d76f08111417f95610f8e27c7af3aa4c4d20abd9

We should use it instead of `Client.GetCurrentUser`.

File: protonmail/auth.go [hunk 2]
```diff
@@ -260,6 +260,53 @@ func (c *Client) Unlock(auth *Auth, passphrase string) (openpgp.EntityList, erro
...
+	for _, e := range u.Addresses {
+		for _, f := range e.Keys {
+			pkey, err := f.Entity()
+			if err != nil {
+				return nil, err
+			}
+			if pkey.PrimaryKey.KeyId == keyRing[0].PrimaryKey.KeyId {
+				continue
+			}
+			prKey, err := openpgp.ReadArmoredKeyRing(strings.NewReader(f.PrivateKey))
```
Comment (emersion) [inline protonmail/auth.go]: You can just call `f.Entity()`

**Comment by emersion** [comment]
Bump

**Comment by emersion** [comment]
Thanks!
