### PR TITLE
protonmail: Fix sending messages after API update.

### LINKED ISSUE #20: 554 Error: transaction failed, blame it on the weather: unknown sender address
This is the only result I get when trying to send anything. I tried with Mutt, plain msmtp, ClawsMail, sendEmail.

example (values in `[]` are hidden by me); hydroxide runs in background and reports nothing apart from `Starting SMTP server at 127.0.0.1:1465`:

```
$ sendEmail -f '[login]@protonmail.com' -t '[receiver]' -m 'test' -s localhost:1465 -l /tmp/smtp.log -xu '[login]' -xp '[password]' -vvv
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => Connecting to localhost:1465
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => My IP address is: 127.0.0.1
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 220 localhost ESMTP Service Ready
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 220
Jan 09 13:24:21 localhost sendEmail[15925]: SUCCESS => Received: 	220 localhost ESMTP Service Ready
Jan 09 13:24:21 localhost sendEmail[15925]: INFO => Sending: 	EHLO localhost.localdomain
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 250-Hello localhost.localdomain
250-PIPELINING
250-8BITMIME
250 AUTH PLAIN
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 250
Jan 09 13:24:21 localhost sendEmail[15925]: SUCCESS => Received: 	250-Hello localhost.localdomain
250-PIPELINING
250-8BITMIME
250 AUTH PLAIN
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => The remote SMTP server does NOT support TLS :(
Jan 09 13:24:21 localhost sendEmail[15925]: DEBUG => SMTP-AUTH: Using PLAIN authentication method
Jan 09 13:24:21 localhost sendEmail[15925]: INFO => Sending: 	AUTH PLAIN [authentication]
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 235 Authentication succeeded
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 235
Jan 09 13:24:22 localhost sendEmail[15925]: SUCCESS => Received: 	235 Authentication succeeded
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => User authentication was successful (Method: PLAIN)
Jan 09 13:24:22 localhost sendEmail[15925]: INFO => Sending: 	MAIL FROM:<[login]@protonmail.com>
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 250 Roger, accepting mail from <[login]@protonmail.com>
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 250
Jan 09 13:24:22 localhost sendEmail[15925]: SUCCESS => Received: 	250 Roger, accepting mail from <[login]@protonmail.com>
Jan 09 13:24:22 localhost sendEmail[15925]: INFO => Sending: 	RCPT TO:<[receiver]>
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 250 I'll make sure <[receiver]> gets this
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 250
Jan 09 13:24:22 localhost sendEmail[15925]: SUCCESS => Received: 	250 I'll make sure <[receiver]> gets this
Jan 09 13:24:22 localhost sendEmail[15925]: INFO => Sending: 	DATA
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 354 Go ahead. End your data with <CR><LF>.<CR><LF>
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP success code: 354
Jan 09 13:24:22 localhost sendEmail[15925]: SUCCESS => Received: 	354 Go ahead. End your data with <CR><LF>.<CR><LF>
Jan 09 13:24:22 localhost sendEmail[15925]: INFO => Sending message body
Jan 09 13:24:22 localhost sendEmail[15925]: Setting content-type: text/plain
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Checking for SMTP success or error status in the message: 554 Error: transaction failed, blame it on the weather: unknown sender address
Jan 09 13:24:22 localhost sendEmail[15925]: DEBUG => evalSMTPresponse() - Found SMTP error code: 554
Jan 09 13:24:22 localhost sendEmail[15925]: ERROR => Received: 	554 Error: transaction failed, blame it on the weather: unknown sender address

```

### PR DESCRIPTION
**Pull request by scelaris**
Fixes enough of the protonmail API to send SMTP messages. Not all SMTP-related commands are fixed; for example, UpdateDraftMessage needs message ID added to outermost-level of request. Fixes #20

### CODE REVIEW

File: protonmail/messages.go [hunk 1]
```diff
@@ -403,7 +403,7 @@ type MessagePackageSet struct {
 	Body      string // Encrypted body data packet
 
 	// Only if cleartext is sent
-	BodyKey        string
+	BodyKey        map[string]string
```
Comment (emersion) [inline protonmail/messages.go]: This should be a struct:

```go
BodyKey *MessageBodyKey `json:omitempty`
```

With a new type `MessageBodyKey` containing the appropriate fields (`Algorithm`, `Key`).

File: protonmail/users.go [hunk 2]
```diff
@@ -70,13 +70,28 @@ func (c *Client) GetCurrentUser() (*User, error) {
...
 		resp
 		User *User
 	}
-	if err := c.doJSON(req, &respData); err != nil {
+	if err := c.doJSON(req, &userData); err != nil {
 		return nil, err
 	}
 
-	return respData.User, nil
+	req2, err := c.newRequest(http.MethodGet, "/addresses", nil)
```
Comment (emersion) [inline protonmail/users.go]: No need to name this `req2`, you can just overwrite `req` (with `=` instead of `:=`)

File: protonmail/users.go [hunk 3]
```diff
@@ -70,13 +70,28 @@ func (c *Client) GetCurrentUser() (*User, error) {
...
+
+	var addrData struct {
+		resp
+		Addresses []*Address
+	}
+	if err := c.doJSON(req2, &addrData); err != nil {
+		return nil, err
+	}
+
+	userData.User.Addresses = addrData.Addresses
```
Comment (emersion) [inline protonmail/users.go]: We should probably remove the `Addresses` field from the `User` struct. This can be left as a follow-up issue though.

File: protonmail/users.go (hunk 2 above)
Comment (scelaris) [reply protonmail/users.go]: My mistake. First time using Go :+1:

File: protonmail/messages.go [hunk 4]
```diff
@@ -403,14 +403,19 @@ type MessagePackageSet struct {
 	Body      string // Encrypted body data packet
 
 	// Only if cleartext is sent
-	BodyKey        string
+	BodyKey        *MessageBodyKey `json:omitempty`
```
Comment (emersion) [inline protonmail/messages.go]: Ah, sorry, it should be:

```go
BodyKey *MessageBodyKey `json:",omitempty"`
```

**Comment by emersion** [comment]
Thanks!
